name: chaostreff-scheduler
version: 0.0.2
synopsis: schedule chaostreff events
license: MIT

ghc-options: -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints -Wmissing-signatures -fprint-potential-instances

default-extensions: OverloadedStrings, NoImplicitPrelude

dependencies:
  - base
  - directory
  - filepath
  - megaparsec
  - optparse-applicative
  - process
  - protolude
  - text
  - time
  - unix

executable:
  main: Main.hs
  source-dirs: src

tests:
  doctest:
    main: doctest.hs
    dependencies:
      - doctest
